# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install python version 2
  hosts: ubuntu
  gather_facts: no
  tasks:
  - name: Install python version 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: result
    changed_when: result.rc != 0
    become: true

- name: Add epel repository on centos
  hosts: centos
  tasks:
  - name: Install epel-release package
    package:
      name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
      state: present
    become: true

- name: Prepare block storage device
  hosts: all
  become: true
  tasks:
  - name: Create loopback device image
    shell: fallocate -l 1073741824 /tmp/dolo.img
    changed_when: false
    tags:
    - skip_ansible_lint

  - name: Create loopback device image
    shell: losetup /dev/loop0 /tmp/dolo.img
    changed_when: false
    become: true
    tags:
    - skip_ansible_lint

- name: Playbook for role testing (cadvisor type docker)
  hosts: all
  vars:
    docker_configure_cadvisor: yes
    docker_listen_on_loopback: yes
    docker_operator_user: "{{ ansible_user }}"
    docker_run_tests: yes

  roles:
  - role: ansible-betacloud.docker

- name: Playbook for role testing (cadvisor type service)
  hosts: all
  vars:
    cadvisor_type: service
    docker_configure_cadvisor: yes
    docker_listen_on_loopback: yes
    docker_operator_user: "{{ ansible_user }}"
    docker_run_tests: no

  roles:
  - role: ansible-betacloud.docker

- name: Playbook for role testing (cadvisor disabled)
  hosts: all
  vars:
    docker_configure_cadvisor: no
    docker_listen_on_loopback: yes
    docker_operator_user: "{{ ansible_user }}"
    docker_run_tests: no

  roles:
  - role: ansible-betacloud.docker
