---
- hosts: ubuntu
  gather_facts: no
  tasks:
  - name: Install python version 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: result
    changed_when: result.rc != 0
    become: true

- hosts: ubuntu
  vars:
    docker_operator_user: ubuntu
    docker_run_cadvisor: yes
    docker_run_tests: yes
    use_docker_as_privileged_user: yes

  roles:
  - role: ansible-betacloud.docker

- hosts: centos
  vars:
    docker_operator_user: centos
    docker_run_cadvisor: yes
    docker_run_tests: yes
    use_docker_as_privileged_user: yes

  roles:
  - role: ansible-betacloud.docker
