# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install python-passlib package
  package:
    name: python-passlib
    state: present
  become: true

- name: Create cadvisor configuration directory
  file:
    path: /etc/cadvisor
    state: directory
    owner: root
    group: root
    mode: 0750
  become: true
  when: "cadvisor_username != ''"

- name: Create htpasswd file for cadvisor
  htpasswd:
    path: /etc/cadvisor/htpasswd
    name: "{{ cadvisor_username }}"
    password: "{{ cadvisor_password }}"
    owner: root
    group: root
    mode: 0640
  become: true
  when: "cadvisor_username != ''"

- name: Prepare cadvisor command
  set_fact:
    cadvisor_command: "-docker_only -disable_metrics='disk'"

- name: Add http auth details to cadvisor command
  set_fact:
    cadvisor_command: "{{ cadvisor_command }} -http_auth_file /etc/cadvisor/htpasswd -http_auth_realm 'cadvisor@{{ inventory_hostname }}'"
  when: "cadvisor_username != ''"

- name: Add influxdb connection details to cadvisor command
  set_fact:
    cadvisor_command: "{{ cadvisor_command }} -storage_driver=influxdb -storage_driver_host={{ cadvisor_influxdb_host }}:{{ cadvisor_influxdb_port }} -storage_driver_db={{ cadvisor_influxdb_database }} -storage_driver_user={{ cadvisor_influxdb_user }} -storage_driver_password={{ cadvisor_influxdb_password }}"
  when: cadvisor_configure_influxdb|bool

- include: "cadvisor-{{ cadvisor_type }}.yml"
