# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Remove cadvisor container
  docker_container:
    name: bc-cadvisor
    image: "google/cadvisor:{{ cadvisor_version }}"
    state: absent
  become: "{{ use_docker_as_privileged_user }}"

- name: Copy cadvisor binary
  copy:
    src: cadvisor
    dest: /usr/local/bin/cadvisor
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy cadvisor service file
  template:
    src: cadvisor.service.j2
    dest: /etc/systemd/system/cadvisor.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: Start/enable cadvisor service
  systemd:
    daemon_reload: yes
    name: cadvisor
    state: started
    enabled: yes
  become: true
