# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Stop/disable cadvisor service
  service:
    name: cadvisor
    state: stopped
    enabled: no
  register: result
  failed_when: "result|failed and 'Could not find the requested service' not in result.msg"
  become: true

- name: Remove cadvisor container
  docker_container:
    name: bc-cadvisor
    image: "google/cadvisor:{{ cadvisor_version }}"
    state: absent
  become: "{{ use_docker_as_privileged_user }}"
