---
- name: Create plugins directory
  file:
    path: /etc/docker/plugins
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Create systemd overlay directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy systemd overlay file
  template:
    src: overlay.conf.j2
    dest: /etc/systemd/system/docker.service.d/overlay.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart docker service
  become: true

- name: Copy limits configuration file
  copy:
    src: limits.conf
    dest: /etc/security/limits.d/docker.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy daemon.json configuration file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart docker service
  become: true

- meta: flush_handlers
