# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Add repository gpg key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  become: true

- name: Add repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    state: present
    update_cache: yes
  become: true

- name: Install linux-image-extra kernel package
  package:
    name: linux-image-extra-virtual
    state: present
  become: true

- name: Install required python modules
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-docker
    - python-ipaddress
  become: true

- name: Add * to docker_version
  set_fact:
    docker_version: "{{ docker_version }}*"
