# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Add repository gpg key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  become: true

- name: Add repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    state: present
    update_cache: yes
  become: true

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - linux-image-extra-virtual
    - python-docker
    - python-ipaddress
  become: true

- name: Install docker-engine package
  apt:
    name: "docker-engine={{ docker_version }}*"
    state: present
  become: true

- name: Hold docker-engine package
  command: apt-mark hold docker-engine
  register: result
  changed_when: "'was already set on hold' not in result.stdout"
  become: true
