---
- name: Include storage tasks
  include: storage.yml
  when: docker_configure_storage_block_device|bool

- name: Include compose install tasks
  include: "install-compose-{{ docker_compose_install_type }}.yml"

- name: Include docker install tasks
  include: "install-docker-{{ ansible_os_family }}.yml"

- name: Include config tasks
  include: config.yml

- name: Include service tasks
  include: service.yml

- name: Include bootstrap tasks
  include: bootstrap.yml
