# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Get status of ufw
  command: ufw status
  become: true
  register: ufw_status
  ignore_errors: true
  changed_when: false

- name: Set docker_configure_ufw fact
  set_fact:
    ufw_active: "'Status: active' in ufw_stats.stdout"

- name: Allow incoming traffic
  ufw:
    interface: docker0
    rule: allow
    direction: in
  when: ufw_active|bool
  become: true
