# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Add repository gpg key
  apt_key:
    url: "{{ docker_debian_repository_key }}"
  become: true

- name: Add repository
  apt_repository:
    repo: "{{ docker_debian_repository }}"
    state: present
    update_cache: yes
  become: true

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ docker_required_packages }}"

- name: Install docker-engine package
  apt:
    name: "docker-engine={{ docker_version }}*"
    state: present
  become: true

- name: Hold docker-engine package
  command: apt-mark hold docker-engine
  register: result
  changed_when: "'was already set on hold' not in result.stdout"
  become: true
