---
- name: Add repository
  yum_repository:
    name: docker
    description: "Docker repository"
    baseurl: "{{ docker_redhat_repository }}"
    state: present
    gpgkey: "{{ docker_redhat_repository_key }}"
    gpgcheck: yes
  become: true
  when: docker_configure_repository|bool

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ docker_required_packages }}"

- name: Unlock package
  command: "yum versionlock del {{ docker_package_name }}"
  register: result
  changed_when: "'versionlock deleted: 1' in result.stdout"
  failed_when: result.rc not in [0,1]
  become: true
  tags:
    - skip_ansible_lint

- name: Install package
  yum:
    name: "{{ docker_engine_package }}-{{ docker_version }}.ce"
    state: present
  become: true

- name: Lock package
  command: "yum versionlock add {{ docker_package_name }}"
  register: result
  changed_when: "'versionlock added: 1' in result.stdout"
  become: true
  tags:
    - skip_ansible_lint
