---
- name: Install apt-transport-https package
  apt:
    name: apt-transport-https
    state: present
  become: true
  when: docker_configure_repository|bool
  changed_when: false

- name: Add repository gpg key
  apt_key:
    url: "{{ docker_debian_repository_key }}"
  become: true
  when: docker_configure_repository|bool

- name: Add repository
  apt_repository:
    repo: "{{ docker_debian_repository }}"
    state: present
    update_cache: yes
  become: true
  when: docker_configure_repository|bool

- name: Pin package version
  copy:
    content: |
      Package: {{ docker_package_name }}
      Pin: version {{ docker_version }}*
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/docker
  become: true

- name: Install package
  apt:
    name: "{{ docker_package_name }}={{ docker_version }}*"
    state: present
  become: true

- name: Ensure docker-compose is not installed
  apt:
    name: docker-compose
    state: absent
  become: true

- name: Block installation of docker-compose package
  copy:
    content: |
      Package: docker-compose
      Pin: version *
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/docker-compose
  become: true

# FIXME(berendt): Add support for bionic release.

- name: Remove python-docker package (openstack_version != ocata)
  package:
    name: python-docker
    state: absent
  become: true
  when: "openstack_version != 'ocata'"

- name: Block installation of python-docker package (openstack_version != ocata)
  copy:
    content: |
      Package: python-docker
      Pin: version *
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/python-docker
  become: true
  when: "openstack_version != 'ocata'"

- name: Install python-docker package (openstack_version == ocata)
  package:
    name: python-docker
    state: present
  become: true
  when: "openstack_version == 'ocata'"

- name: Install python-pip package
  package:
    name: python-pip
    state: present
  become: true
  when: "openstack_version != 'ocata'"

- name: Install docker package (openstack_version != ocata)
  pip:
    name: "{{ docker_pip_package_name }}"
    extra_args: "{{ docker_pip_extra_args }}"
    executable: pip
    state: present
  become: true
  when: "openstack_version != 'ocata'"
