---
- name: Install apt-transport-https package
  apt:
    name: apt-transport-https
    state: present
  become: true
  when: docker_configure_repository|bool
  changed_when: false

- name: Add repository gpg key
  apt_key:
    url: "{{ docker_debian_repository_key }}"
  become: true
  when: docker_configure_repository|bool

- name: Add repository
  apt_repository:
    repo: "{{ docker_debian_repository }}"
    state: present
    update_cache: yes
  become: true
  when: docker_configure_repository|bool

- name: Pin package version
  copy:
    content: |
      Package: {{ docker_package_name }}
      Pin: version {{ docker_version }}*
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/docker
  become: true

- name: Pin cli package version
  copy:
    content: |
      Package: {{ docker_package_name }}-cli
      Pin: version {{ docker_version }}*
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/docker-cli
  become: true

- name: Install package
  apt:
    name: "{{ docker_package_name }}={{ docker_version }}*"
    state: present
  become: true

- name: Ensure docker-compose is not installed
  apt:
    name: docker-compose
    state: absent
  become: true

- name: Block installation of docker-compose package
  copy:
    content: |
      Package: docker-compose
      Pin: version *
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/docker-compose
  become: true

- name: Install python bindings with apt
  block:
    - name: Unblock installation of python docker packages
      file:
        dest: "/etc/apt/preferences.d/{{ item }}"
        state: absent
      with_items: "{{ docker_python_package_names }}"

    - name: Install python docker packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ docker_python_package_names }}"

  become: true
  when: not docker_python_install_from_pip|bool

- name: Install python bindings with pip
  block:
    - name: Remove python docker packages (install python bindings from pip)
      package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ docker_python_package_names }}"

    - name: Block installation of python docker packages (install python bindings from pip)
      copy:
        content: |
          Package: {{ item }}
          Pin: version *
          Pin-Priority: -1
        dest: "/etc/apt/preferences.d/{{ item }}"
      with_items: "{{ docker_python_package_names }}"

    - name: Install python-pip package (install python bindings from pip)
      package:
        name: python-pip
        state: present

    - name: Install docker packages (install python bindings from pip)
      pip:
        name: "{{ docker_pip_package_name }}"
        extra_args: "{{ docker_pip_extra_args }}"
        executable: pip
        state: present

  become: true
  when: docker_python_install_from_pip|bool
