---
- name: Install apt-transport-https package
  package:
    name: apt-transport-https
    state: present
  become: true

- name: Add repository gpg key
  apt_key:
    url: "{{ docker_debian_repository_key }}"
  become: true
  when: docker_configure_repository|bool

- name: Add repository
  apt_repository:
    repo: "{{ docker_debian_repository }}"
    state: present
    update_cache: yes
  become: true
  when: docker_configure_repository|bool

- name: Pin package version
  copy:
    content: |
      Package: {{ docker_package_name }}
      Pin: version {{ docker_version }}*
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/docker
  become: true

- name: Install package
  apt:
    name: "{{ docker_package_name }}={{ docker_version }}*"
    state: present
  become: true

- name: Ensure docker-compose is not installed
  apt:
    name: docker-compose
    state: absent
  become: true

- name: Block installation of docker-compose package
  copy:
    content: |
      Package: docker-compose
      Pin: version *
      Pin-Priority: -1
    dest: /etc/apt/preferences.d/docker-compose
  become: true
