---
- name: Add repository gpg key
  apt_key:
    url: "{{ docker_debian_repository_key }}"
  become: true
  when: docker_configure_repository|bool

- name: Add repository
  apt_repository:
    repo: "{{ docker_debian_repository }}"
    state: present
    update_cache: yes
  become: true
  when: docker_configure_repository|bool

- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ docker_required_packages }}"

- name: Install package
  apt:
    name: "{{ docker_package_name }}={{ docker_version }}*"
    state: present
  become: true

- name: Hold package
  command: "apt-mark hold {{ docker_package_name }}"
  register: result
  changed_when: "'was already set on hold' not in result.stdout"
  become: true

- name: Ensure docker-compose is not installed
  apt:
    name: docker-compose
    state: absent
  become: true

- name: Set hold on docker-compose package
  command: apt-mark hold docker-compose
  register: result
  changed_when: "'was already set on hold' not in result.stdout"
  become: true
