---
- name: Gather the apt package facts
  package_facts:
    manager: auto

- name: Check whether packages are installed that should not be installed
  fail:
    msg: "{{ ansible_facts.packages[item] | length }} versions of {{ item }} are installed!"
  when: "item in ansible_facts.packages"
  with_items: "{{ docker_packages_fail }}"

- name: Install apt-transport-https package
  apt:
    name: apt-transport-https
    state: present
  become: true
  when: docker_configure_repository|bool
  changed_when: false

- name: Add repository gpg key
  apt_key:
    url: "{{ docker_debian_repository_key }}"
  become: true
  when: docker_configure_repository|bool

- name: Add repository
  apt_repository:
    repo: "{{ docker_debian_repository }}"
    state: present
    update_cache: yes
  become: true
  when: docker_configure_repository|bool

- name: Pin package version
  copy:
    content: |
      Package: {{ docker_package_name }}
      Pin: version {{ docker_version }}*
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/docker
  become: true

- name: Pin cli package version
  copy:
    content: |
      Package: {{ docker_package_name }}-cli
      Pin: version {{ docker_version }}*
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/docker-cli
  become: true

- name: Unlock containerd package
  dpkg_selections:
    name: "{{ containerd_package_name }}"
    selection: install
  become: true
  tags: molecule-idempotence-notest

# NOTE: At this point the last available version of containerd should be installed
- name: Install containerd package
  apt:
    name: "{{ containerd_package_name }}"
    state: latest
  become: true  # noqa 403

- name: Lock containerd package
  dpkg_selections:
    name: "{{ containerd_package_name }}"
    selection: hold
  become: true
  tags: molecule-idempotence-notest

- name: Install docker-cli package
  apt:
    name: "{{ docker_cli_package_name }}={{ docker_version }}*"
    state: present
  become: true

- name: Install docker package
  apt:
    name: "{{ docker_package_name }}={{ docker_version }}*"
    state: present
  become: true

- name: Install python bindings with apt
  block:
    - name: Unblock installation of python docker packages
      file:
        dest: "/etc/apt/preferences.d/{{ item }}"
        state: absent
      with_items: "{{ docker_python_package_names }}"

    - name: Install python docker package
      package:
        name: "{{ docker_python_package_name }}"
        state: present
      when: "ansible_distribution_release in ['xenial', 'bionic']"

    - name: Install python3 docker package
      package:
        name: "{{ docker_python3_package_name }}"
        state: present

  become: true
  when: not docker_python_install_from_pip|bool

- name: Install python bindings with pip
  block:
    - name: Remove python docker packages (install python bindings from pip)
      package:
        name: "{{ item }}"
        state: absent
      with_items: "{{ docker_python_package_names }}"

    - name: Block installation of python docker packages (install python bindings from pip)
      copy:
        content: |
          Package: {{ item }}
          Pin: version *
          Pin-Priority: -1
        dest: "/etc/apt/preferences.d/{{ item }}"
      with_items: "{{ docker_python_package_names }}"

    - name: Install python-pip package (install python bindings from pip)
      package:
        name: python-pip
        state: present

    - name: Install docker packages (install python bindings from pip)
      pip:
        name: "{{ docker_pip_package_name }}"
        extra_args: "{{ docker_pip_extra_args }}"
        executable: pip
        state: present

  become: true
  when: docker_python_install_from_pip|bool

- name: Install packages required by docker login
  package:
    name: "{{ item }}"
    state: present
  loop:
    - gnupg2
    - pass
  become: true
  when:
    - docker_registry_username is defined and docker_registry_username|length > 0
    - docker_registry_password is defined and docker_registry_password|length > 0
