# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Include storage tasks
  include: storage.yml
  when: docker_storage_block_device|default("") != ""

- name: Include distribution specifc tasks
  include: "{{ ansible_os_family }}.yml"

- name: Create plugins directory
  file:
    path: /etc/docker/plugins
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Create systemd overlay directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy systemd overlay file
  template:
    src: overlay.conf.j2
    dest: /etc/systemd/system/docker.service.d/overlay.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart docker service
  become: true

- name: Copy limits configuration file
  copy:
    src: limits.conf
    dest: /etc/security/limits.d/docker.conf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Copy daemon.json configuration file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Restart docker service
  become: true

- meta: flush_handlers

- name: Start/Enable service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Start/Enable docker socket service
  service:
    name: docker.socket
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'
  become: true

- name: Include firewall tasks
  include: "firewall-{{ ansible_os_family }}.yml"

- name: Add user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  when: docker_user != ""
  become: true

# NOTE: use paramiko connection to force a re-login

- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    reauthorize: yes
  when:
    - docker_user != ""
    - docker_registry_username|default("") != ""
    - docker_registry_password|default("") != ""
  connection: paramiko

- name: Ensure docker is working like expected
  include: test.yml
  when: docker_run_tests|bool
