# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Include distribution specific variables
  include_vars: "vars/{{ ansible_os_family }}.yml"

- include: "{{ action }}.yml"

- name: Ensure docker is working like expected
  include: test.yml
  when: docker_run_tests|bool
