---
- name: docker - start/enable service
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: docker - start/enable docker socket service
  service:
    name: docker.socket
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'
  become: true
