# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Pull an image
  docker_image:
    name: alpine
  become: "{{ docker_as_privileged_user }}"
  connection: paramiko

- name: Start a container
  docker_container:
    name: sleepy
    image: alpine
    command: sleep infinity
  become: "{{ docker_as_privileged_user }}"
  connection: paramiko

- name: Remove a container
  docker_container:
    name: sleepy
    state: absent
  become: "{{ docker_as_privileged_user }}"
  connection: paramiko

- name: Remove image
  docker_image:
    name: alpine
    state: absent
  become: "{{ docker_as_privileged_user }}"
  connection: paramiko
