---
- name: Install python version 2
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python version 2 on ubuntu
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    become: true

- name: Add epel repository on centos
  hosts: all

  tasks:
  - name: Install epel-release package
    package:
      name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
      state: present
    become: true
    when: ansible_os_family == "RedHat"

- name: Prepare block storage device
  hosts: all
  become: true

  tasks:
  - name: Create loopback device image
    shell: fallocate -l 1073741824 /tmp/dolo.img
    changed_when: false
    ignore_errors: yes
    tags:
    - skip_ansible_lint

  - name: Create loopback device image
    shell: losetup /dev/loop0 /tmp/dolo.img
    changed_when: false
    become: true
    ignore_errors: yes
    tags:
    - skip_ansible_lint

- name: Playbook for role testing (cadvisor type docker)
  hosts: all

  vars:
    cadvisor: yes
    docker_listen_on_loopback: yes
    docker_run_tests: yes
    docker_storage_block_device: /dev/loop0
    use_docker_as_privileged_user: yes

  roles:
    - role: "../../ansible-docker"

- name: Playbook for role testing (cadvisor type service)
  hosts: all

  vars:
    cadvisor: yes
    cadvisor_type: service
    docker_listen_on_loopback: yes
    docker_run_tests: no
    docker_storage_block_device: /dev/loop0
    use_docker_as_privileged_user: yes

  roles:
    - role: "../../ansible-docker"

- name: Playbook for role testing (cadvisor disabled)
  hosts: all

  vars:
    cadvisor: no
    docker_listen_on_loopback: yes
    docker_run_tests: no
    docker_storage_block_device: /dev/loop0
    use_docker_as_privileged_user: yes

  roles:
    - role: "../../ansible-docker"
