# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Install python version 2 on ubuntu
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python version 2 on ubuntu
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    register: result
    changed_when: result.rc != 0
    become: true

- name: Prepare block storage device
  hosts: all
  become: true

  tasks:
  - name: Create loopback device image
    shell: fallocate -l 1073741824 /tmp/dolo.img
    changed_when: false
    ignore_errors: yes
    tags:
    - skip_ansible_lint

  - name: Create loopback device image
    shell: losetup /dev/loop0 /tmp/dolo.img
    changed_when: false
    become: true
    ignore_errors: yes
    tags:
    - skip_ansible_lint

- name: Playbook for role testing
  hosts: all

  vars:
    docker_listen_on_loopback: yes
    docker_storage_block_device: /dev/loop0

  pre_tasks:
  - name: Add epel repository
    yum_repository:
      name: epel
      description: EPEL
      baseurl: "https://download.fedoraproject.org/pub/epel/$releasever/$basearch/"
      gpgkey: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
    become: true
    when: ansible_os_family == 'RedHat'

  - name: Include vagrant variables
    include_vars: vars/vagrant.yml

  roles:
    - role: ../../ansible-docker
