---
- name: Install python version 2
  hosts: all
  gather_facts: no

  tasks:
  - name: Install python version 2 on ubuntu
    raw: test -e /usr/bin/python || (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal))
    become: true

- name: Prepare block storage device
  hosts: all
  become: true

  tasks:
  - name: Create loopback device image
    shell: fallocate -l 1073741824 /tmp/dolo.img
    changed_when: false
    ignore_errors: yes
    tags:
    - skip_ansible_lint

  - name: Create loopback device image
    shell: losetup /dev/loop0 /tmp/dolo.img
    changed_when: false
    become: true
    ignore_errors: yes
    tags:
    - skip_ansible_lint

- name: Playbook for role testing
  hosts: all

  vars:
    docker_listen_on_loopback: yes
    docker_run_tests: yes
    docker_storage_block_device: /dev/loop0

  roles:
    - role: "../../ansible-docker"
