# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.
---
- name: Restart docker service
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ docker_service_name }}"
  become: true
