---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: molecule-ubuntu-docker
    image: solita/ubuntu-systemd
    image_version: 16.04
    command: /sbin/init
  - name: molecule-centos-docker
    image: centos/systemd
    image_version: latest
    command: /usr/sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
