---
- name: Playbook for role testing
  hosts: all

  vars:
    docker_compose_install_from_url: yes
    docker_configure_storage_block_device: yes
    docker_storage_block_device: /dev/loop0
    docker_opts:
      mtu: 0
      selinux-enabled: false
      dns-search:
        - betacloud.xyz
        - osism.xyz

  roles:
    - role: ansible-docker
