---
- name: Prepare instance for use with Ansible
  hosts: all
  gather_facts: false

  tasks:
  - name: A short pause, in order to be sure the instance is ready
    pause:
      seconds: 10

  - name: Install required packages
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: true
    changed_when: false

- name: Playbook for role preparations
  hosts: all

  vars:
    device_size: 1G
    device_file: /tmp/docker.img
    device_name: loop0

  tasks:
    - name: Load loop kernel module
      modprobe:
        name: loop
      become: true

    - name: Create loopback device image
      command: fallocate -l {{ device_size }} {{ device_file }} creates={{ device_file }}

    - name: Setup loopback device
      command: losetup /dev/{{ device_name }} {{ device_file }}
      become: true
